### ISSUE TITLE
we need README.md & CONTRIBUTING.md

### ISSUE THREAD

**Issue by 2pai** [2pai-dev/animoji#1]
we need README.md 
reference:https://github.com/brittanyrw/emojiscreen/blob/master/README.md
and for CONTRIBUTING.md
reference : https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md

comment to this issue if you want take this PR

**Comment by pr0ph0z** [comment]
Can I take README.md?

**Comment by 2pai** [comment]
> Can I take README.md?

sure go ahead

**Comment by YogaSakti** [comment]
I take CONTRIBUTING.md

**Comment by 2pai** [comment]
> I take CONTRIBUTING.md

sure

**Comment by 2pai** [comment]
don't forget to mention this badge @pr0ph0z 

[![Netlify Status](https://api.netlify.com/api/v1/badges/4ffec391-b69c-409a-90f7-76fbf4970020/deploy-status)](https://app.netlify.com/sites/animoji/deploys)

**Comment by pr0ph0z** [comment]
noted

**Comment by 2pai** [comment]
thanks @pr0ph0z @YogaSakti
