### ISSUE TITLE
link contributor button to animoji repository 

### ISSUE THREAD

**Issue by 2pai** [2pai-dev/animoji#11]
the goal is make this button redirect to this github repository
![image](https://user-images.githubusercontent.com/22183588/65889897-35fb3580-e3cc-11e9-8afa-47c2db04dba8.png)

**Comment by shivansh2598** [comment]
Hey, I would like to contribute.

**Comment by 2pai** [comment]
sure , it's yours

**Comment by 2pai** [comment]
fixed on #12 
thanks @shivansh2598
