### ISSUE TITLE
Fix emojis 

### ISSUE THREAD

**Issue by 2pai** [2pai-dev/animoji#20]
there's anime who have more than 5 emojis 
![image](https://user-images.githubusercontent.com/22183588/65935115-1c94d080-e442-11e9-9ca3-d78f78abec13.png)

the goal is to edit the emojis, and make sure that emojis is < 5

**Comment by the-bose** [comment]
I'd like to work on this

**Comment by the-bose** [comment]
It would be nice if you mention in the CONTRIBUTING.MD about the emoji limit to avoid future discrepancies.

**Comment by 2pai** [comment]
> It would be nice if you mention in the CONTRIBUTING.MD about the emoji limit to avoid future discrepancies.

can you mention this on CONTRIBUTING.MD ? that would be helpful
