### ISSUE TITLE
Create Integration Test & CI Pipeline

### ISSUE THREAD

**Issue by 2pai** [2pai-dev/animoji#297]
Create Integration Test & CI Pipeline to make sure the length of emojis is less or equal than 8.
We can use Github actions as a CI pipeline
This issue aims to avoid this case : 
![image](https://user-images.githubusercontent.com/22183588/96364840-e61e1680-1166-11eb-9a86-beda5b5b6d43.png)

**Comment by pr0ph0z** [comment]
Hi, I would like to take this issue 🥂

**Comment by 2pai** [comment]
@pr0ph0z sure, go ahead!
