### ISSUE TITLE
Emoji Issue

### ISSUE THREAD

**Issue by pr0ph0z** [2pai-dev/animoji#298]
As you may know, I assigned to #297 but when I started to work that out, I found (and realized) that Emoji is not a simple string like characters we know. It is Unicode. 
So I proposed this issue be fixed first before fixing #297.

reference: https://thekevinscott.com/emojis-in-javascript/

**Comment by 2pai** [comment]
Thank you @pr0ph0z for the improvement. 
yup, I think that would be a separate issue for the context issue.
