### ISSUE TITLE
Standardize File Names

### ISSUE THREAD

**Issue by pr0ph0z** [2pai-dev/animoji#311]
As you can see, there are a lot of file names with an inconsistent pattern. Should we standardize submitted file names under `src/datasource/`? Using kebab-case maybe?

**Comment by 2pai** [comment]
That's good, maybe we should update the template PR & other documents too. 

Should we create an integration test to make sure the CI Fails when the filename isn't correct?

**Comment by pr0ph0z** [comment]
That would be great! Can I take this issue as well?

**Comment by 2pai** [comment]
@pr0ph0z Sure, go ahead!

**Comment by pr0ph0z** [comment]
Should I write out to which file caused the test to fail? e.g `Haikyuu To The Top isn't in proper case!`

**Comment by 2pai** [comment]
That's nice, feel free to open the PR @pr0ph0z

**Comment by pr0ph0z** [comment]
Closed via #312
